# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-05 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='url',
        ),
    ]
