# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-08 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0002_remove_counter_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='server',
            field=models.CharField(default=b'Server Unknown', max_length=200),
        ),
    ]
