# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-14 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0003_counter_server'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='counter',
            table='COUNTERS',
        ),
    ]
